apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runners-hi-frontend
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/RocketDDan/frontend.git
    targetRevision: HEAD
    path: deploy/k8s   # ← 매니페스트 폴더
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: runners-hi
  project: default
  syncPolicy:
    automated:
      prune: true       # 선택: Git에서 제거된 리소스도 함께 삭제
      selfHeal: true    # 선택: 클러스터 드리프트 자동 복구