apiVersion: apps/v1
kind: Deployment
metadata:
  name: runners-hi-frontend
  # namespace: frontend
  labels:
    app: runners-hi-frontend
spec:
  replicas: 3  # 필요에 따라 복제 개수 늘리기
  selector:
    matchLabels:
      app: runners-hi-frontend
  template:
    metadata:
      labels:
        app: runners-hi-frontend
    spec:
      containers:
      - name: frontend
        image: hanol98/runners-hi-frontend:143
        ports:
        - containerPort: 80
        # readinessProbe/livenessProbe 등 추가 가능