apiVersion: v1
kind: Service
metadata:
  name: runners-hi-frontend
  # namespace: frontend
spec:
  type: NodePort
  selector:
    app: runners-hi-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000